import json
from pathlib import Path

from devctl.override import ensure_override_stub, override_path, remove_override, write_override
from devctl.profiles import PublishTarget

from .helpers import TempDirTestCase, make_profile, make_settings

HEADER = "# generated by devctl -- do not edit\n"


class OverrideTests(TempDirTestCase):
    def setUp(self) -> None:
        super().setUp()
        self.settings = make_settings(self.tmp_path)
        self.profile = make_profile(
            name="app",
            http_port_env=None,
            publish=PublishTarget(service="web", container_port=80),
        )

    def read_document(self, path: Path) -> dict:
        text = path.read_text(encoding="utf-8")
        self.assertTrue(text.startswith(HEADER))
        return json.loads(text[len(HEADER) :])

    def test_write_override_renders_publish_host_port_and_service(self) -> None:
        path = write_override(self.settings, self.profile, 50003)

        self.assertEqual(self.settings.state_dir / "overrides" / "app.yml", path)
        self.assertEqual(
            {"services": {"web": {"ports": ["127.0.0.1:50003:80"]}}},
            self.read_document(path),
        )

    def test_ensure_override_stub_creates_empty_services_file_once(self) -> None:
        path = ensure_override_stub(self.settings, self.profile)

        self.assertEqual(override_path(self.settings, self.profile.name), path)
        self.assertEqual({"services": {}}, self.read_document(path))

    def test_ensure_override_stub_keeps_existing_content(self) -> None:
        write_override(self.settings, self.profile, 50003)

        path = ensure_override_stub(self.settings, self.profile)

        self.assertIn("50003", path.read_text(encoding="utf-8"))

    def test_write_override_appends_publish_port_to_fragment_service(self) -> None:
        fragment = {"services": {"web": {"ports": ["127.0.0.1:50010:5173"]}}}
        profile = make_profile(
            name="app",
            http_port_env=None,
            publish=PublishTarget(service="web", container_port=80),
            compose_override=fragment,
        )

        document = self.read_document(write_override(self.settings, profile, 50003))

        self.assertEqual(
            ["127.0.0.1:50010:5173", "127.0.0.1:50003:80"],
            document["services"]["web"]["ports"],
        )
        self.assertEqual({"services": {"web": {"ports": ["127.0.0.1:50010:5173"]}}}, fragment)

    def test_write_override_renders_fragment_services_networks_and_volumes(self) -> None:
        profile = make_profile(
            name="app",
            http_port_env=None,
            publish=PublishTarget(service="web", container_port=80),
            compose_override={
                "services": {"db": {"image": "mysql:8.0.33"}},
                "networks": {"proxy": {"external": False, "name": "app-proxy"}},
                "volumes": {"db-data": None},
            },
        )

        document = self.read_document(write_override(self.settings, profile, 50003))

        self.assertEqual({"image": "mysql:8.0.33"}, document["services"]["db"])
        self.assertEqual(["127.0.0.1:50003:80"], document["services"]["web"]["ports"])
        self.assertEqual({"proxy": {"external": False, "name": "app-proxy"}}, document["networks"])
        self.assertEqual({"db-data": None}, document["volumes"])

    def test_stub_contains_fragment_without_publish_port(self) -> None:
        profile = make_profile(
            name="app",
            http_port_env=None,
            publish=PublishTarget(service="web", container_port=80),
            compose_override={"services": {"db": {"image": "mysql:8.0.33"}}},
        )

        document = self.read_document(ensure_override_stub(self.settings, profile))

        self.assertEqual({"services": {"db": {"image": "mysql:8.0.33"}}}, document)

    def test_write_override_for_env_mode_profile_renders_fragment_only(self) -> None:
        profile = make_profile(
            name="app",
            compose_override={"services": {"db": {"image": "mysql:8.0.33"}}},
        )

        document = self.read_document(write_override(self.settings, profile, 50003))

        self.assertEqual({"services": {"db": {"image": "mysql:8.0.33"}}}, document)

    def test_remove_override_deletes_the_generated_file(self) -> None:
        path = write_override(self.settings, self.profile, 50003)
        self.assertTrue(path.exists())

        remove_override(self.settings, self.profile.name)

        self.assertFalse(path.exists())

    def test_remove_override_is_a_noop_when_the_file_does_not_exist(self) -> None:
        remove_override(self.settings, "never-existed")

    def test_remove_override_ignores_names_with_path_separators(self) -> None:
        (self.settings.state_dir / "overrides").mkdir(parents=True)
        outside_target = self.settings.state_dir.parent / "evil.yml"
        outside_target.write_text("do not delete me", encoding="utf-8")

        remove_override(self.settings, "../../evil")

        self.assertTrue(outside_target.exists())

    def test_write_override_does_not_leave_a_tmp_file_behind(self) -> None:
        write_override(self.settings, self.profile, 50003)

        leftovers = list((self.settings.state_dir / "overrides").glob("*.tmp"))
        self.assertEqual([], leftovers)

    def test_write_override_rejects_profile_without_publish_or_compose_override(self) -> None:
        profile = make_profile(name="app")

        with self.assertRaises(AssertionError):
            write_override(self.settings, profile, 50003)
