import json
from copy import deepcopy
from pathlib import Path

from .profiles import PROFILE_NAME_PATTERN, ProjectProfile
from .settings import Settings

_HEADER = "# generated by devctl -- do not edit\n"


def override_path(settings: Settings, name: str) -> Path:
    return settings.state_dir / "overrides" / f"{name}.yml"


def _render(settings: Settings, profile: ProjectProfile, backend_port: int | None) -> str:
    document = deepcopy(profile.compose_override) if profile.compose_override else {}
    services = document.setdefault("services", {})
    if backend_port is not None and profile.publish:
        service = services.setdefault(profile.publish.service, {})
        ports = service.setdefault("ports", [])
        ports.append(f"{settings.publish_host}:{backend_port}:{profile.publish.container_port}")
    return _HEADER + json.dumps(document, indent=2) + "\n"


def _write(settings: Settings, profile: ProjectProfile, backend_port: int | None) -> Path:
    path = override_path(settings, profile.name)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_name(f"{path.name}.tmp")
    tmp_path.write_text(_render(settings, profile, backend_port), encoding="utf-8")
    tmp_path.replace(path)
    return path


def write_override(settings: Settings, profile: ProjectProfile, backend_port: int) -> Path:
    if profile.publish is None and not profile.compose_override:
        raise AssertionError("write_override requires profile.publish or profile.compose_override")
    return _write(settings, profile, backend_port)


def ensure_override_stub(settings: Settings, profile: ProjectProfile) -> Path:
    path = override_path(settings, profile.name)
    if not path.exists():
        _write(settings, profile, None)
    return path


def remove_override(settings: Settings, name: str) -> None:
    if not PROFILE_NAME_PATTERN.fullmatch(name):
        return
    override_path(settings, name).unlink(missing_ok=True)
